sidebar
akai-org/wosp-puszki pull request #37
Opened 2022-11-10 11:50 UTC by pawelbartosik

first version of sidebar to check

2022-11-11 11:38 UTC, Safeheaded commented on client/src/App.tsx
> +      <div>
Delete the initial, pregenerated content. We don't need it and honestly, it only ruins the experience

2022-11-11 11:46 UTC, Safeheaded commented on client/src/components/Layout/Sidebar.tsx
> +        <a href="">Strona Główna</a>
Change <a> tags to react-router <NavLink /> tags. Also add detection of currently active page (styles like on hover). Here are the docs: https://reactrouter.com/en/main/components/nav-link

2022-11-11 11:57 UTC, Safeheaded requested changes
Overall - good job. Please make specified adjustments. And delete the counter state too. If you run into any problem - ask here or on discord.

2022-11-11 11:57 UTC, Safeheaded commented on client/src/components/Layout/Sidebar.tsx
> +    <Layout className={`${styles.sidebar} ${styles['sidebar-layout']}`}>
To apply multiple classes it's better to use this syntax: className={[styles.classOne, styles.classTwo].join(' ')}. And better use camelCase in classes names - you avoid the styles['class-name'] syntax.

2022-11-11 11:57 UTC, Safeheaded commented on client/src/components/Layout/Sidebar.tsx
> +        <a href="">Strona Główna</a>
Change tags to react-router tags. Also add detection of currently active page (styles like on hover). Here are the docs: https://reactrouter.com/en/main/components/nav-link

2022-11-11 11:57 UTC, Safeheaded commented on client/src/App.tsx
> +      <div>
Delete the initial, pregenerated content. We don't need it and honestly, it only ruins the experience

2022-11-11 17:43 UTC, Now4czyk commented
According to [mockups](https://www.figma.com/file/dHaZSnxQiLIyLVXauwrApR/WO%C5%9AP?node-id=1%3A3) I assume that there should be 2 views of sidebar: for users that are logged in and for these that are not(view with LoginForm). Please, consider adding a property that controlls switching between these two.

2022-11-12 16:47 UTC, Safeheaded requested changes
Almost there! Minor fixes left and we're good to go. And please, delete package-lock.json and yarn.lock from the main directory

2022-11-12 16:47 UTC, Safeheaded commented on client/src/components/Layout/Sidebar.tsx
> +const bookmarks = [
Misleading names - these are links, not bookmarks

2022-11-12 16:47 UTC, Safeheaded commented on client/src/components/Layout/Sidebar.tsx
> +  { name: 'Strona Główna', url: '#home' },
Delete '#' from urls. And it's a good idea to click through your changes to be 100% they're working before commiting ;)

2022-11-12 16:47 UTC, Safeheaded commented on client/src/components/Layout/Sidebar.tsx
> +    <Fragment>
Would be good idea to reformat this code into two components, due to low readibility. E.g. <ProtectedContent /> and <UnprotectedContent />

2022-11-12 16:47 UTC, Safeheaded commented on client/src/components/Layout/SidebarItem.tsx
> +  const location = useLocation();
No need to use `useLocation`. NavLink has built in way of detecting if link is active. Read the [docs](https://reactrouter.com/en/main/components/nav-link) and if any questions appear - hit me up

2022-11-12 16:49 UTC, Safeheaded commented on client/src/components/Layout/Sidebar.tsx
> +    <Fragment>
Github has eaten part of my comment. Here's how it should have been: E.g. `<ProtectedContent />` and `<UnprotectedContent />`.

2022-11-13 18:15 UTC, Safeheaded approved these changes
Well done! Can finally merge!

2022-11-13 19:30 UTC, merged